name: Update Bluesky Feed

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

jobs:
  update-feed:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate Bluesky feed
      env:
        BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
        BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
      run: npm run generate:bluesky
    
    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet public/data/bluesky-feed.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add public/data/bluesky-feed.json public/data/bluesky-feed-summary.json
        git commit -m "🤖 Update Bluesky feed [skip ci]"
        git push