name: Update Bluesky Feed
on:
  schedule:
    - cron: '0 * * * *' # hourly
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate Bluesky feed
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: node scripts/generate-bluesky-feed.js

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Create a new branch
          BRANCH_NAME="bot/update-bluesky-feed-$(date +%s)"
          git checkout -b $BRANCH_NAME
          
          # Create directories for Ghost's expected location
          mkdir -p content/files
          
          # Copy to Ghost's actual file serving location
          cp public/data/bluesky-feed.json content/files/bluesky-feed.json
          cp public/data/bluesky-feed-summary.json content/files/bluesky-feed-summary.json
          
          # Check if anything changed and add files with force flag
          git add -f content/files/bluesky-feed*.json
          
          if git diff --cached --quiet; then
            echo "No changes detected in content/files/"
            exit 0
          fi
          
          # Commit the changes
          git commit -m "🤖 Update Bluesky feed"
          
          # Push the new branch
          git push origin $BRANCH_NAME
          
          # Create a pull request
          gh pr create --title "🤖 Update Bluesky feed" --body "Automated update of the Bluesky feed."
