name: Update Bluesky Feed

on:
  schedule:
    - cron: '0 * * * *'   # hourly
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Bluesky feed
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: node scripts/generate-bluesky-feed.js

      - name: Commit and push if changed
        run: |
          set -e
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          # Ensure we're diffing against the latest main
          git fetch origin main

          # If nothing changed, skip committing
          if git diff --quiet origin/main -- public/data/bluesky-feed.json public/data/bluesky-feed-summary.json; then
            echo "No changes vs origin/main."
            exit 0
          fi

          git add public/data/bluesky-feed.json public/data/bluesky-feed-summary.json
          git commit -m "🤖 Update Bluesky feed [skip ci]"

          # Avoid non-fast-forward errors
          git pull --rebase origin main

          git push origin HEAD:main
