name: Update Bluesky Feed
on:
  schedule:
    - cron: '0 * * * *' # hourly
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          # Remove old lock file and regenerate it
          rm -f package-lock.json
          npm install
          # Commit the new lock file if it changed
          if ! git diff --quiet package-lock.json; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add package-lock.json
            git commit -m "📦 Update package-lock.json after cleanup"
            git push origin main
          fi

      - name: Generate Bluesky feed
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: node scripts/generate-bluesky-feed.js

      - name: Commit and push if changed
        run: |
          set -e
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Debug: Show what files exist
          echo "=== Files in current directory ==="
          find . -name "*bluesky*" -type f
          echo "=== End file listing ==="
          
          # Ensure we're diffing against the latest main
          git fetch origin main
          
          # Create the content/files directory for Ghost
          mkdir -p content/files
          echo "Created content/files directory"
          
          # Check if source files exist and copy them
          if [ -f public/data/bluesky-feed.json ]; then
            echo "Found source files, copying..."
            cp public/data/bluesky-feed.json content/files/bluesky-feed.json
            cp public/data/bluesky-feed-summary.json content/files/bluesky-feed-summary.json
            echo "Successfully copied files to content/files/"
            
            # Verify the files were copied
            if [ -f content/files/bluesky-feed.json ]; then
              echo "✓ content/files/bluesky-feed.json exists"
              echo "File size: $(wc -c < content/files/bluesky-feed.json) bytes"
            else
              echo "✗ Failed to create content/files/bluesky-feed.json"
              exit 1
            fi
          else
            echo "✗ Source files not found in public/data/"
            echo "Available files:"
            ls -la public/data/ || echo "public/data/ directory doesn't exist"
            exit 1
          fi
          
          # Check if anything changed in the target location
          git add content/files/bluesky-feed.json content/files/bluesky-feed-summary.json
          
          if git diff --cached --quiet; then
            echo "No changes detected in content/files/"
            exit 0
          fi
          
          # Commit the changes
          git commit -m "🤖 Update Bluesky feed [skip ci]"
          echo "Changes committed"
          
          # Avoid non-fast-forward errors
          git pull --rebase origin main
          git push origin HEAD:main
          echo "Changes pushed successfully"
